ALTER TABLE shop_inventory ADD COLUMN IF NOT EXISTS "typeLine" TEXT;
ALTER TABLE shop_inventory ADD COLUMN IF NOT EXISTS colors TEXT;
ALTER TABLE shop_inventory ADD COLUMN IF NOT EXISTS cmc DOUBLE PRECISION;
ALTER TABLE shop_inventory ADD COLUMN IF NOT EXISTS rarity TEXT;
